### ISSUE TITLE
Unvailable "Tune" feature control property crashes app

### ISSUE THREAD

**Issue by gerwindehaan** [lvsti/Cameo#3]
Thanks for the recent effort of swift-wrapping (and more) of CoreMediaIO. In the unmodified code for this app, I get a crash when clicking the Adjust Control button.

Digging in, I see a `Control.model` doesn't initialize properly, leading to a failed initialization of any `AdjustControlPanelController`... This is a failable initializer and returns nil, but explicitly unwrapped in `showAdjustControlPanel`, leading to a crash when setting its delegate. A guard would be effective here to avoid the crash, but the cause itself is more interesting:

In my experiments the following code segment in `Control.model` always fails:
`case .boolean(let isTuning) = FeatureControlProperty.tune.value(in: controlID)`. When I comment that part, I can continue working with the app and explore my cameras and controls. 

BTW I haven't seen the FourCC 'fctn' / `kCMIOFeatureControlPropertyTune` be available anywhere in my connected camera's/controls on MacOS 10.14.6 Mojave.

**Comment by lvsti** [comment]
Hi, I've just bumped CMIOKit which now contains the fix. As for Tune, I also found that it's not available in any of the controls I see but I don't know the reason.
