### ISSUE TITLE
How do i give you money

### ISSUE THREAD

**Issue by johnboiles** [lvsti/Cameo#4]
This project is great and I would like to fund some beer for you :D

**Comment by lvsti** [comment]
Haha that's very kind of you, let's say I'll let you invite me for one if one shiny day we coincide in SF, Budapest, or anywhere else in the world. 🙂

**Comment by johnboiles** [comment]
Haha sounds delightful. Budapest is beautiful; I've visited a couple of times.

But seriously if you ever put a donate button here ping me.
